services:
  inkly-api:
    image: inkly
    build: .
    container_name: inkly-api
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
      - inkly_node_modules:/app/node_modules
    depends_on:
      inkly-mongo:
        condition: service_healthy
    command: npm run dev
    restart: unless-stopped

  inkly-mongo:
    image: mongo:7
    container_name: inkly-mongo
    ports:
      - "27017:27017"
    volumes:
      - inkly_mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  inkly_mongo_data:
  inkly_node_modules:
